version: "3.7"

services:
  traefik:
    build: "traefik"
    container_name: "traefik"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  static-app:
    build: "static"
    container_name: "static-app"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-app.entrypoints=web,web-secure"
      - "traefik.http.routers.static-app.rule=PathPrefix(`/`)"
      - "traefik.http.services.static-app.loadbalancer.server.port=80"

  glaciers-app:
    image: "oggm/bokeh:20191106"
    container_name: "glaciers-app"
    command:
      - "git+https://github.com/TimoRoth/glaciers.git"
      - "glaciers.ipynb"
    environment:
      - "BOKEH_PREFIX=/glaciers"
      - "BOKEH_ALLOW_WS_ORIGIN=${WS_ORIGIN}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glaciers-app.entrypoints=web,web-secure"
      - "traefik.http.routers.glaciers-app.rule=PathPrefix(`/glaciers`)"
      - "traefik.http.services.glaciers-app.loadbalancer.server.port=8080"
