version: "3.7"

services:
  traefik:
    image: "traefik:v2.0"
    container_name: "traefik"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${ACME_DIR}:/etc/traefik/acme"
    command:
      - "--log.level=info"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web-secure.address=:443"
      - "--certificatesResolvers.leres.acme.email=${ACME_EMAIL}"
      - "--certificatesResolvers.leres.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesResolvers.leres.acme.tlsChallenge=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${LE_DOMAIN}`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.routers.web.middlewares=redirect-https"

  static-app:
    build: "static"
    container_name: "static-app"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.static-app.loadbalancer.server.port=80"
      - "traefik.http.routers.static-app.entrypoints=web-secure"
      - "traefik.http.routers.static-app.rule=PathPrefix(`/`)"
      - "traefik.http.routers.static-app.tls.certResolver=leres"
      - "traefik.http.routers.static-app.tls.domains[0].main=${LE_DOMAIN}"

  glaciers-app:
    image: "oggm/bokeh:20191106"
    container_name: "glaciers-app"
    command:
      - "git+https://github.com/TimoRoth/glaciers.git@a37ba155b657a8b273dd913d472d6a90c68d9733"
      - "glaciers.ipynb"
    environment:
      - "BOKEH_PREFIX=/glaciers"
      - "BOKEH_ALLOW_WS_ORIGIN=${WS_ORIGIN}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.glaciers-app.loadbalancer.server.port=8080"
      - "traefik.http.routers.glaciers-app.entrypoints=web-secure"
      - "traefik.http.routers.glaciers-app.rule=PathPrefix(`/glaciers`)"
      - "traefik.http.routers.glaciers-app.tls.certResolver=leres"
      - "traefik.http.routers.glaciers-app.tls.domains[0].main=${LE_DOMAIN}"

  simulator-app:
    image: "oggm/bokeh:20191106"
    container_name: "simulator-app"
    command:
      - "git+https://github.com/pat-schmitt/glacier_simulator.git@8dccae7e3f31950936f63e04caf504b99816c068"
      - "simulator.ipynb"
    environment:
      - "BOKEH_PREFIX=/simulator"
      - "BOKEH_ALLOW_WS_ORIGIN=${WS_ORIGIN}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.simulator-app.loadbalancer.server.port=8080"
      - "traefik.http.routers.simulator-app.entrypoints=web-secure"
      - "traefik.http.routers.simulator-app.rule=PathPrefix(`/simulator`)"
      - "traefik.http.routers.simulator-app.tls.certResolver=leres"
      - "traefik.http.routers.simulator-app.tls.domains[0].main=${LE_DOMAIN}"

  explorer-app:
    image: "oggm/bokeh:20191106"
    container_name: "explorer-app"
    command:
      - "git+https://github.com/zschirmeister/glacier-explorer.git@d04d442f97b4b7a0c79b62943708cbc9debb982a"
      - "glaciers-explorer-panel.ipynb"
    environment:
      - "BOKEH_PREFIX=/explorer"
      - "BOKEH_ALLOW_WS_ORIGIN=${WS_ORIGIN}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.explorer-app.entrypoints=web-secure"
      - "traefik.http.routers.explorer-app.rule=PathPrefix(`/explorer`)"
      - "traefik.http.routers.explorer-app.tls.certResolver=leres"
      - "traefik.http.services.explorer-app.loadbalancer.server.port=8080"
      - "traefik.http.routers.explorer-app.tls.domains[0].main=${LE_DOMAIN}"
